config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/angular', to: 'portfolios#angular', as: 'portfolio_angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root "pages#home"
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body

    belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  layout 'blog'
  
  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
    @page_title = 'Blogs'
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: 'Blog was successfully changed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.title %></td>
  <td><%= distance_of_time_in_words_to_now(blog.created_at) %> ago</td>
  <td><%= blog.body %></td>
  <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) if logged_in?(:site_admin) %></td>
  <td><%= button_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<%= link_to "New blog", new_blog_path if logged_in?(:site_admin) %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @blog %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) if logged_in?(:site_admin) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete if logged_in?(:site_admin) %>
</div>