config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/angular', to: 'portfolios#angular', as: 'portfolio_angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                    reject_if: lambda { |attrs| attrs['name'].blank? }

    include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image

    # forma 1
    def self.angular
        where(subtitle: "Angular")
    end

    # forma 2
    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }


    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: "600", width: "400")
        self.thumb_image ||= Placeholder.image_generator(height: "350", width: "200")
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  layout 'portfolio'

  def index
    @portfolios = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build }
  end

  def create
    @portfolio = Portfolio.new(portfolios_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolios_params)
        format.html { redirect_to portfolios_path, notice: "portfolio was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio was successfully destroyed." }
    end
  end

  private
    def portfolios_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body, 
                                        technologies_attributes: [:name]
                                        )
    end

    def set_portfolio_item
      @portfolio = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <ul>
      <%= form.fields_for :technologies do |technology_form| %>
        <li>
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name %>
        </li>
      <% end %>
    </ul>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>

<p><%= portfolio.subtitle %></p>

<p><%= portfolio.body %></p>

<%#= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>

<%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>

<%= button_to "Destroy", portfolio, method: :delete if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create new item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio| %>
    <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>
    <p><%= portfolio.subtitle %></p>
    <p><%= portfolio.body %></p>
    <%#= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>
    <%= button_to "Destroy", portfolio, method: :delete if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio</h1>

<%= link_to "Volver", portfolios_path %>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin) %>

<%= render @portfolios %>

app/views/portfolios/new.html.erb
<h1>Create Portfolio</h1>

<%= link_to "Volver", portfolios_path %>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<h1>Show <%= @portfolio.title %></h1>

<%= link_to "Volver", portfolios_path %>

<%= render @portfolio %>
<%# <%= render partial: 'portfolio_name', collection: @portfolio_name %> %>

<h2>Technologies used:</h2>

<% @portfolio.technologies.each do |tech| %>
    <p><%= tech.name %></p>
<% end %>

<%= link_to "Edit", edit_portfolio_path(@portfolio.id) if logged_in?(:site_admin) %>