config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/angular', to: 'portfolios#angular', as: 'portfolio_angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root "pages#home"
end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50">
    <p><%= copyright %></p>
</footer>

app/views/shared/_application_nav.html.erb
<header class="mb-auto">
    <div>
        <h3 class="float-md-start mb-0">Alexander Herrera</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
            <%= link_to "Home", root_path, class: 'nav-link' %>
            <%= link_to "Blog", blogs_path, class: 'nav-link' %>
            <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
            <%= link_to "About", about_path, class: 'nav-link' %>
            <%= link_to "Contact", contact_path, class: 'nav-link' %>
            <%= login_helper 'nav-link' %>
        </nav>
    </div>
</header>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
    <div><% link_to "Home", root_path %></div>
    <div><% link_to "Blog", blogs_path %></div>
    <div><% link_to "Portfolio", portfolios_path %></div>
    <div><% link_to "About", about_path %></div>
    <div><% link_to "Contact", contact_path %></div>
</div>